version: "3.9"

services:
  libvirt-container:
    container_name: libvirt-container
    tty: true
    privileged: true
    environment:
      - LIBVIRT_CONFIG_PATH=/libvirt-container/backend/.config.yml
    volumes:
      - .\backend\src:/libvirt-container/backend/src
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /libvirt-container/backend
    build:
      dockerfile: Dockerfile
    image: compose-libvirt
    ports:
      - 8080:8000
      - 2211:22

#   libvirt-webserver:
#     container_name: libvirt-webserver
#     tty: true
#     build:
#       context: ./nginx
#       dockerfile: Dockerfile
#     ports:
#       - 18000:80
#     networks:
#       - libvirt-app-network


# networks:
#   libvirt-app-network:
#     driver: bridge