version: "3.9"

services:
  libvirt-container:
    container_name: libvirt-container
    tty: true
    environment:
      - LIBVIRT_CONFIG_PATH=/libvirt-container/backend/.config.yml
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /libvirt-container/backend
    build:
      dockerfile: Dockerfile
    image: compose-libvirt
    ports:
      - 18080:80
